site_name: pseudo/pseudo
nav:
  - Home: Home.md
  - Pseudo\Pdo: classes/Pseudo/Pdo.md
  - Pseudo\PdoStatement: classes/Pseudo/PdoStatement.md
  - Pseudo\Result: classes/Pseudo/Result.md
  - Pseudo\ParsedQuery: classes/Pseudo/ParsedQuery.md
theme: readthedocs
